ALTER TABLE nki ALTER COLUMN patient        TYPE FLOAT;
ALTER TABLE nki ALTER COLUMN id             TYPE FLOAT;
ALTER TABLE nki ALTER COLUMN age            TYPE FLOAT;
ALTER TABLE nki ALTER COLUMN eventdeath     TYPE FLOAT;
ALTER TABLE nki ALTER COLUMN survival       TYPE FLOAT;
ALTER TABLE nki ALTER COLUMN timerecurrence TYPE FLOAT;
ALTER TABLE nki ALTER COLUMN chemo          TYPE FLOAT;
ALTER TABLE nki ALTER COLUMN hormonal       TYPE FLOAT;
ALTER TABLE nki ALTER COLUMN amputation     TYPE FLOAT;
ALTER TABLE nki ALTER COLUMN histtype       TYPE FLOAT;
ALTER TABLE nki ALTER COLUMN diam           TYPE FLOAT;
ALTER TABLE nki ALTER COLUMN posnodes       TYPE FLOAT;
ALTER TABLE nki ALTER COLUMN grade          TYPE FLOAT;
ALTER TABLE nki ALTER COLUMN angioinv       TYPE FLOAT;
ALTER TABLE nki ALTER COLUMN lymphinfil     TYPE FLOAT;



